/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the PaginatedStackEnvVarList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedStackEnvVarList{}

// PaginatedStackEnvVarList struct for PaginatedStackEnvVarList
type PaginatedStackEnvVarList struct {
	// Object count in the collection
	Count *int32 `json:"@count,omitempty"`
	// A reference to the next page of results. The property is included until there are no more pages of results to retrieve.
	NextLink *string `json:"@nextLink,omitempty"`
	// List of the resulting values
	Value                []StackEnvVar `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedStackEnvVarList PaginatedStackEnvVarList

// NewPaginatedStackEnvVarList instantiates a new PaginatedStackEnvVarList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedStackEnvVarList(value []StackEnvVar) *PaginatedStackEnvVarList {
	this := PaginatedStackEnvVarList{}
	this.Value = value
	return &this
}

// NewPaginatedStackEnvVarListWithDefaults instantiates a new PaginatedStackEnvVarList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedStackEnvVarListWithDefaults() *PaginatedStackEnvVarList {
	this := PaginatedStackEnvVarList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedStackEnvVarList) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedStackEnvVarList) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedStackEnvVarList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PaginatedStackEnvVarList) SetCount(v int32) {
	o.Count = &v
}

// GetNextLink returns the NextLink field value if set, zero value otherwise.
func (o *PaginatedStackEnvVarList) GetNextLink() string {
	if o == nil || IsNil(o.NextLink) {
		var ret string
		return ret
	}
	return *o.NextLink
}

// GetNextLinkOk returns a tuple with the NextLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedStackEnvVarList) GetNextLinkOk() (*string, bool) {
	if o == nil || IsNil(o.NextLink) {
		return nil, false
	}
	return o.NextLink, true
}

// HasNextLink returns a boolean if a field has been set.
func (o *PaginatedStackEnvVarList) HasNextLink() bool {
	if o != nil && !IsNil(o.NextLink) {
		return true
	}

	return false
}

// SetNextLink gets a reference to the given string and assigns it to the NextLink field.
func (o *PaginatedStackEnvVarList) SetNextLink(v string) {
	o.NextLink = &v
}

// GetValue returns the Value field value
func (o *PaginatedStackEnvVarList) GetValue() []StackEnvVar {
	if o == nil {
		var ret []StackEnvVar
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaginatedStackEnvVarList) GetValueOk() ([]StackEnvVar, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *PaginatedStackEnvVarList) SetValue(v []StackEnvVar) {
	o.Value = v
}

func (o PaginatedStackEnvVarList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedStackEnvVarList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["@count"] = o.Count
	}
	if !IsNil(o.NextLink) {
		toSerialize["@nextLink"] = o.NextLink
	}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedStackEnvVarList) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varPaginatedStackEnvVarList := _PaginatedStackEnvVarList{}

	err = json.Unmarshal(data, &varPaginatedStackEnvVarList)

	if err != nil {
		return err
	}

	*o = PaginatedStackEnvVarList(varPaginatedStackEnvVarList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "@count")
		delete(additionalProperties, "@nextLink")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedStackEnvVarList struct {
	value *PaginatedStackEnvVarList
	isSet bool
}

func (v NullablePaginatedStackEnvVarList) Get() *PaginatedStackEnvVarList {
	return v.value
}

func (v *NullablePaginatedStackEnvVarList) Set(val *PaginatedStackEnvVarList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedStackEnvVarList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedStackEnvVarList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedStackEnvVarList(val *PaginatedStackEnvVarList) *NullablePaginatedStackEnvVarList {
	return &NullablePaginatedStackEnvVarList{value: val, isSet: true}
}

func (v NullablePaginatedStackEnvVarList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedStackEnvVarList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
