/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the CreateStackEnvVarRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStackEnvVarRequestRequest{}

// CreateStackEnvVarRequestRequest struct for CreateStackEnvVarRequestRequest
type CreateStackEnvVarRequestRequest struct {
	// Name of the variable.
	Name string `json:"name"`
	// Variable value.
	Value string `json:"value"`
	// Description of the variable.
	Description          NullableString `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateStackEnvVarRequestRequest CreateStackEnvVarRequestRequest

// NewCreateStackEnvVarRequestRequest instantiates a new CreateStackEnvVarRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStackEnvVarRequestRequest(name string, value string) *CreateStackEnvVarRequestRequest {
	this := CreateStackEnvVarRequestRequest{}
	this.Name = name
	this.Value = value
	return &this
}

// NewCreateStackEnvVarRequestRequestWithDefaults instantiates a new CreateStackEnvVarRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStackEnvVarRequestRequestWithDefaults() *CreateStackEnvVarRequestRequest {
	this := CreateStackEnvVarRequestRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateStackEnvVarRequestRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateStackEnvVarRequestRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateStackEnvVarRequestRequest) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CreateStackEnvVarRequestRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateStackEnvVarRequestRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CreateStackEnvVarRequestRequest) SetValue(v string) {
	o.Value = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateStackEnvVarRequestRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateStackEnvVarRequestRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateStackEnvVarRequestRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateStackEnvVarRequestRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateStackEnvVarRequestRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateStackEnvVarRequestRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o CreateStackEnvVarRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStackEnvVarRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateStackEnvVarRequestRequest) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varCreateStackEnvVarRequestRequest := _CreateStackEnvVarRequestRequest{}

	err = json.Unmarshal(data, &varCreateStackEnvVarRequestRequest)

	if err != nil {
		return err
	}

	*o = CreateStackEnvVarRequestRequest(varCreateStackEnvVarRequestRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateStackEnvVarRequestRequest struct {
	value *CreateStackEnvVarRequestRequest
	isSet bool
}

func (v NullableCreateStackEnvVarRequestRequest) Get() *CreateStackEnvVarRequestRequest {
	return v.value
}

func (v *NullableCreateStackEnvVarRequestRequest) Set(val *CreateStackEnvVarRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStackEnvVarRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStackEnvVarRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStackEnvVarRequestRequest(val *CreateStackEnvVarRequestRequest) *NullableCreateStackEnvVarRequestRequest {
	return &NullableCreateStackEnvVarRequestRequest{value: val, isSet: true}
}

func (v NullableCreateStackEnvVarRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStackEnvVarRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
