/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
	"time"
)

// checks if the ScheduleEnds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleEnds{}

// ScheduleEnds struct for ScheduleEnds
type ScheduleEnds struct {
	// A datetime instance specifying the upper-bound limit of the recurrence.
	OnDate *time.Time `json:"on_date,omitempty"`
	// Determines how many times the schedule will start the test.
	AfterRuns            *int32 `json:"after_runs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScheduleEnds ScheduleEnds

// NewScheduleEnds instantiates a new ScheduleEnds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleEnds() *ScheduleEnds {
	this := ScheduleEnds{}
	return &this
}

// NewScheduleEndsWithDefaults instantiates a new ScheduleEnds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleEndsWithDefaults() *ScheduleEnds {
	this := ScheduleEnds{}
	return &this
}

// GetOnDate returns the OnDate field value if set, zero value otherwise.
func (o *ScheduleEnds) GetOnDate() time.Time {
	if o == nil || IsNil(o.OnDate) {
		var ret time.Time
		return ret
	}
	return *o.OnDate
}

// GetOnDateOk returns a tuple with the OnDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleEnds) GetOnDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OnDate) {
		return nil, false
	}
	return o.OnDate, true
}

// HasOnDate returns a boolean if a field has been set.
func (o *ScheduleEnds) HasOnDate() bool {
	if o != nil && !IsNil(o.OnDate) {
		return true
	}

	return false
}

// SetOnDate gets a reference to the given time.Time and assigns it to the OnDate field.
func (o *ScheduleEnds) SetOnDate(v time.Time) {
	o.OnDate = &v
}

// GetAfterRuns returns the AfterRuns field value if set, zero value otherwise.
func (o *ScheduleEnds) GetAfterRuns() int32 {
	if o == nil || IsNil(o.AfterRuns) {
		var ret int32
		return ret
	}
	return *o.AfterRuns
}

// GetAfterRunsOk returns a tuple with the AfterRuns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleEnds) GetAfterRunsOk() (*int32, bool) {
	if o == nil || IsNil(o.AfterRuns) {
		return nil, false
	}
	return o.AfterRuns, true
}

// HasAfterRuns returns a boolean if a field has been set.
func (o *ScheduleEnds) HasAfterRuns() bool {
	if o != nil && !IsNil(o.AfterRuns) {
		return true
	}

	return false
}

// SetAfterRuns gets a reference to the given int32 and assigns it to the AfterRuns field.
func (o *ScheduleEnds) SetAfterRuns(v int32) {
	o.AfterRuns = &v
}

func (o ScheduleEnds) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleEnds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OnDate) {
		toSerialize["on_date"] = o.OnDate
	}
	if !IsNil(o.AfterRuns) {
		toSerialize["after_runs"] = o.AfterRuns
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScheduleEnds) UnmarshalJSON(data []byte) (err error) {
	varScheduleEnds := _ScheduleEnds{}

	err = json.Unmarshal(data, &varScheduleEnds)

	if err != nil {
		return err
	}

	*o = ScheduleEnds(varScheduleEnds)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "on_date")
		delete(additionalProperties, "after_runs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScheduleEnds struct {
	value *ScheduleEnds
	isSet bool
}

func (v NullableScheduleEnds) Get() *ScheduleEnds {
	return v.value
}

func (v *NullableScheduleEnds) Set(val *ScheduleEnds) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleEnds) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleEnds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleEnds(val *ScheduleEnds) *NullableScheduleEnds {
	return &NullableScheduleEnds{value: val, isSet: true}
}

func (v NullableScheduleEnds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleEnds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
