/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the StaticIPAcquireLoadZoneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StaticIPAcquireLoadZoneRequest{}

// StaticIPAcquireLoadZoneRequest struct for StaticIPAcquireLoadZoneRequest
type StaticIPAcquireLoadZoneRequest struct {
	// Name of the load zone.
	LoadZone string `json:"load_zone"`
	// Number of Static IPs to acquire.
	Count                int32 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _StaticIPAcquireLoadZoneRequest StaticIPAcquireLoadZoneRequest

// NewStaticIPAcquireLoadZoneRequest instantiates a new StaticIPAcquireLoadZoneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticIPAcquireLoadZoneRequest(loadZone string, count int32) *StaticIPAcquireLoadZoneRequest {
	this := StaticIPAcquireLoadZoneRequest{}
	this.LoadZone = loadZone
	this.Count = count
	return &this
}

// NewStaticIPAcquireLoadZoneRequestWithDefaults instantiates a new StaticIPAcquireLoadZoneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticIPAcquireLoadZoneRequestWithDefaults() *StaticIPAcquireLoadZoneRequest {
	this := StaticIPAcquireLoadZoneRequest{}
	return &this
}

// GetLoadZone returns the LoadZone field value
func (o *StaticIPAcquireLoadZoneRequest) GetLoadZone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoadZone
}

// GetLoadZoneOk returns a tuple with the LoadZone field value
// and a boolean to check if the value has been set.
func (o *StaticIPAcquireLoadZoneRequest) GetLoadZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoadZone, true
}

// SetLoadZone sets field value
func (o *StaticIPAcquireLoadZoneRequest) SetLoadZone(v string) {
	o.LoadZone = v
}

// GetCount returns the Count field value
func (o *StaticIPAcquireLoadZoneRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *StaticIPAcquireLoadZoneRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *StaticIPAcquireLoadZoneRequest) SetCount(v int32) {
	o.Count = v
}

func (o StaticIPAcquireLoadZoneRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StaticIPAcquireLoadZoneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["load_zone"] = o.LoadZone
	toSerialize["count"] = o.Count

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StaticIPAcquireLoadZoneRequest) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varStaticIPAcquireLoadZoneRequest := _StaticIPAcquireLoadZoneRequest{}

	err = json.Unmarshal(data, &varStaticIPAcquireLoadZoneRequest)

	if err != nil {
		return err
	}

	*o = StaticIPAcquireLoadZoneRequest(varStaticIPAcquireLoadZoneRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "load_zone")
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStaticIPAcquireLoadZoneRequest struct {
	value *StaticIPAcquireLoadZoneRequest
	isSet bool
}

func (v NullableStaticIPAcquireLoadZoneRequest) Get() *StaticIPAcquireLoadZoneRequest {
	return v.value
}

func (v *NullableStaticIPAcquireLoadZoneRequest) Set(val *StaticIPAcquireLoadZoneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticIPAcquireLoadZoneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticIPAcquireLoadZoneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticIPAcquireLoadZoneRequest(val *StaticIPAcquireLoadZoneRequest) *NullableStaticIPAcquireLoadZoneRequest {
	return &NullableStaticIPAcquireLoadZoneRequest{value: val, isSet: true}
}

func (v NullableStaticIPAcquireLoadZoneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticIPAcquireLoadZoneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
