/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the TestRunDistribution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestRunDistribution{}

// TestRunDistribution struct for TestRunDistribution
type TestRunDistribution struct {
	// Name of the load zone.
	LoadZone string `json:"load_zone"`
	// Percentage of the load that runs from the load zone.
	Percent              int32 `json:"percent"`
	AdditionalProperties map[string]interface{}
}

type _TestRunDistribution TestRunDistribution

// NewTestRunDistribution instantiates a new TestRunDistribution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestRunDistribution(loadZone string, percent int32) *TestRunDistribution {
	this := TestRunDistribution{}
	this.LoadZone = loadZone
	this.Percent = percent
	return &this
}

// NewTestRunDistributionWithDefaults instantiates a new TestRunDistribution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestRunDistributionWithDefaults() *TestRunDistribution {
	this := TestRunDistribution{}
	return &this
}

// GetLoadZone returns the LoadZone field value
func (o *TestRunDistribution) GetLoadZone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoadZone
}

// GetLoadZoneOk returns a tuple with the LoadZone field value
// and a boolean to check if the value has been set.
func (o *TestRunDistribution) GetLoadZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoadZone, true
}

// SetLoadZone sets field value
func (o *TestRunDistribution) SetLoadZone(v string) {
	o.LoadZone = v
}

// GetPercent returns the Percent field value
func (o *TestRunDistribution) GetPercent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Percent
}

// GetPercentOk returns a tuple with the Percent field value
// and a boolean to check if the value has been set.
func (o *TestRunDistribution) GetPercentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percent, true
}

// SetPercent sets field value
func (o *TestRunDistribution) SetPercent(v int32) {
	o.Percent = v
}

func (o TestRunDistribution) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestRunDistribution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["load_zone"] = o.LoadZone
	toSerialize["percent"] = o.Percent

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TestRunDistribution) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varTestRunDistribution := _TestRunDistribution{}

	err = json.Unmarshal(data, &varTestRunDistribution)

	if err != nil {
		return err
	}

	*o = TestRunDistribution(varTestRunDistribution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "load_zone")
		delete(additionalProperties, "percent")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestRunDistribution struct {
	value *TestRunDistribution
	isSet bool
}

func (v NullableTestRunDistribution) Get() *TestRunDistribution {
	return v.value
}

func (v *NullableTestRunDistribution) Set(val *TestRunDistribution) {
	v.value = val
	v.isSet = true
}

func (v NullableTestRunDistribution) IsSet() bool {
	return v.isSet
}

func (v *NullableTestRunDistribution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestRunDistribution(val *TestRunDistribution) *NullableTestRunDistribution {
	return &NullableTestRunDistribution{value: val, isSet: true}
}

func (v NullableTestRunDistribution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestRunDistribution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
