/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the ScheduleRepeats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleRepeats{}

// ScheduleRepeats struct for ScheduleRepeats
type ScheduleRepeats struct {
	// The unit type of the recurrence interval.  * `hourly` - hourly * `daily` - daily * `weekly` - weekly * `monthly` - monthly * `yearly` - yearly
	Frequency string `json:"frequency"`
	// The interval between each freq iteration. An interval of 2 with 'hourly' frequency means once every 2 hours.
	Interval *int32 `json:"interval,omitempty"`
	// When given, define the days of the week where the recurrence will be applied. The default is every day of the week.
	Days                 []string `json:"days,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScheduleRepeats ScheduleRepeats

// NewScheduleRepeats instantiates a new ScheduleRepeats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleRepeats(frequency string) *ScheduleRepeats {
	this := ScheduleRepeats{}
	this.Frequency = frequency
	var interval int32 = 1
	this.Interval = &interval
	return &this
}

// NewScheduleRepeatsWithDefaults instantiates a new ScheduleRepeats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleRepeatsWithDefaults() *ScheduleRepeats {
	this := ScheduleRepeats{}
	var interval int32 = 1
	this.Interval = &interval
	return &this
}

// GetFrequency returns the Frequency field value
func (o *ScheduleRepeats) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *ScheduleRepeats) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *ScheduleRepeats) SetFrequency(v string) {
	o.Frequency = v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *ScheduleRepeats) GetInterval() int32 {
	if o == nil || IsNil(o.Interval) {
		var ret int32
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleRepeats) GetIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *ScheduleRepeats) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given int32 and assigns it to the Interval field.
func (o *ScheduleRepeats) SetInterval(v int32) {
	o.Interval = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *ScheduleRepeats) GetDays() []string {
	if o == nil || IsNil(o.Days) {
		var ret []string
		return ret
	}
	return o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleRepeats) GetDaysOk() ([]string, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *ScheduleRepeats) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given []string and assigns it to the Days field.
func (o *ScheduleRepeats) SetDays(v []string) {
	o.Days = v
}

func (o ScheduleRepeats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleRepeats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["frequency"] = o.Frequency
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScheduleRepeats) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varScheduleRepeats := _ScheduleRepeats{}

	err = json.Unmarshal(data, &varScheduleRepeats)

	if err != nil {
		return err
	}

	*o = ScheduleRepeats(varScheduleRepeats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "frequency")
		delete(additionalProperties, "interval")
		delete(additionalProperties, "days")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScheduleRepeats struct {
	value *ScheduleRepeats
	isSet bool
}

func (v NullableScheduleRepeats) Get() *ScheduleRepeats {
	return v.value
}

func (v *NullableScheduleRepeats) Set(val *ScheduleRepeats) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleRepeats) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleRepeats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleRepeats(val *ScheduleRepeats) *NullableScheduleRepeats {
	return &NullableScheduleRepeats{value: val, isSet: true}
}

func (v NullableScheduleRepeats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleRepeats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
