/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
	"time"
)

// checks if the ScheduleCreateRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleCreateRequestRequest{}

// ScheduleCreateRequestRequest struct for ScheduleCreateRequestRequest
type ScheduleCreateRequestRequest struct {
	// Id of the test to run.
	LoadTestId int32 `json:"load_test_id"`
	// The date after which the schedule will start running the test.
	Starts               time.Time                     `json:"starts"`
	Repeats              PatchedScheduleRequestRepeats `json:"repeats"`
	Ends                 PatchedScheduleRequestEnds    `json:"ends"`
	AdditionalProperties map[string]interface{}
}

type _ScheduleCreateRequestRequest ScheduleCreateRequestRequest

// NewScheduleCreateRequestRequest instantiates a new ScheduleCreateRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleCreateRequestRequest(loadTestId int32, starts time.Time, repeats PatchedScheduleRequestRepeats, ends PatchedScheduleRequestEnds) *ScheduleCreateRequestRequest {
	this := ScheduleCreateRequestRequest{}
	this.LoadTestId = loadTestId
	this.Starts = starts
	this.Repeats = repeats
	this.Ends = ends
	return &this
}

// NewScheduleCreateRequestRequestWithDefaults instantiates a new ScheduleCreateRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleCreateRequestRequestWithDefaults() *ScheduleCreateRequestRequest {
	this := ScheduleCreateRequestRequest{}
	return &this
}

// GetLoadTestId returns the LoadTestId field value
func (o *ScheduleCreateRequestRequest) GetLoadTestId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LoadTestId
}

// GetLoadTestIdOk returns a tuple with the LoadTestId field value
// and a boolean to check if the value has been set.
func (o *ScheduleCreateRequestRequest) GetLoadTestIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoadTestId, true
}

// SetLoadTestId sets field value
func (o *ScheduleCreateRequestRequest) SetLoadTestId(v int32) {
	o.LoadTestId = v
}

// GetStarts returns the Starts field value
func (o *ScheduleCreateRequestRequest) GetStarts() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Starts
}

// GetStartsOk returns a tuple with the Starts field value
// and a boolean to check if the value has been set.
func (o *ScheduleCreateRequestRequest) GetStartsOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starts, true
}

// SetStarts sets field value
func (o *ScheduleCreateRequestRequest) SetStarts(v time.Time) {
	o.Starts = v
}

// GetRepeats returns the Repeats field value
func (o *ScheduleCreateRequestRequest) GetRepeats() PatchedScheduleRequestRepeats {
	if o == nil {
		var ret PatchedScheduleRequestRepeats
		return ret
	}

	return o.Repeats
}

// GetRepeatsOk returns a tuple with the Repeats field value
// and a boolean to check if the value has been set.
func (o *ScheduleCreateRequestRequest) GetRepeatsOk() (*PatchedScheduleRequestRepeats, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repeats, true
}

// SetRepeats sets field value
func (o *ScheduleCreateRequestRequest) SetRepeats(v PatchedScheduleRequestRepeats) {
	o.Repeats = v
}

// GetEnds returns the Ends field value
func (o *ScheduleCreateRequestRequest) GetEnds() PatchedScheduleRequestEnds {
	if o == nil {
		var ret PatchedScheduleRequestEnds
		return ret
	}

	return o.Ends
}

// GetEndsOk returns a tuple with the Ends field value
// and a boolean to check if the value has been set.
func (o *ScheduleCreateRequestRequest) GetEndsOk() (*PatchedScheduleRequestEnds, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ends, true
}

// SetEnds sets field value
func (o *ScheduleCreateRequestRequest) SetEnds(v PatchedScheduleRequestEnds) {
	o.Ends = v
}

func (o ScheduleCreateRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleCreateRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["load_test_id"] = o.LoadTestId
	toSerialize["starts"] = o.Starts
	toSerialize["repeats"] = o.Repeats
	toSerialize["ends"] = o.Ends

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScheduleCreateRequestRequest) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varScheduleCreateRequestRequest := _ScheduleCreateRequestRequest{}

	err = json.Unmarshal(data, &varScheduleCreateRequestRequest)

	if err != nil {
		return err
	}

	*o = ScheduleCreateRequestRequest(varScheduleCreateRequestRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "load_test_id")
		delete(additionalProperties, "starts")
		delete(additionalProperties, "repeats")
		delete(additionalProperties, "ends")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScheduleCreateRequestRequest struct {
	value *ScheduleCreateRequestRequest
	isSet bool
}

func (v NullableScheduleCreateRequestRequest) Get() *ScheduleCreateRequestRequest {
	return v.value
}

func (v *NullableScheduleCreateRequestRequest) Set(val *ScheduleCreateRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleCreateRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleCreateRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleCreateRequestRequest(val *ScheduleCreateRequestRequest) *NullableScheduleCreateRequestRequest {
	return &NullableScheduleCreateRequestRequest{value: val, isSet: true}
}

func (v NullableScheduleCreateRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleCreateRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
