/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the ApiErrorDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorDetail{}

// ApiErrorDetail struct for ApiErrorDetail
type ApiErrorDetail struct {
	// Human-readable string describing the error
	Message string `json:"message"`
	// Service-defined error code
	Code string `json:"code"`
	// A string indicating the target of the error, for example, the name of the property in error
	Target               *string `json:"target,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiErrorDetail ApiErrorDetail

// NewApiErrorDetail instantiates a new ApiErrorDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorDetail(message string, code string) *ApiErrorDetail {
	this := ApiErrorDetail{}
	this.Message = message
	this.Code = code
	return &this
}

// NewApiErrorDetailWithDefaults instantiates a new ApiErrorDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorDetailWithDefaults() *ApiErrorDetail {
	this := ApiErrorDetail{}
	return &this
}

// GetMessage returns the Message field value
func (o *ApiErrorDetail) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiErrorDetail) SetMessage(v string) {
	o.Message = v
}

// GetCode returns the Code field value
func (o *ApiErrorDetail) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ApiErrorDetail) SetCode(v string) {
	o.Code = v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *ApiErrorDetail) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *ApiErrorDetail) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *ApiErrorDetail) SetTarget(v string) {
	o.Target = &v
}

func (o ApiErrorDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["code"] = o.Code
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiErrorDetail) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varApiErrorDetail := _ApiErrorDetail{}

	err = json.Unmarshal(data, &varApiErrorDetail)

	if err != nil {
		return err
	}

	*o = ApiErrorDetail(varApiErrorDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "code")
		delete(additionalProperties, "target")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiErrorDetail struct {
	value *ApiErrorDetail
	isSet bool
}

func (v NullableApiErrorDetail) Get() *ApiErrorDetail {
	return v.value
}

func (v *NullableApiErrorDetail) Set(val *ApiErrorDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorDetail(val *ApiErrorDetail) *NullableApiErrorDetail {
	return &NullableApiErrorDetail{value: val, isSet: true}
}

func (v NullableApiErrorDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
