/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the PaginatedLoadTestList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedLoadTestList{}

// PaginatedLoadTestList struct for PaginatedLoadTestList
type PaginatedLoadTestList struct {
	// Object count in the collection
	Count *int32 `json:"@count,omitempty"`
	// A reference to the next page of results. The property is included until there are no more pages of results to retrieve.
	NextLink *string `json:"@nextLink,omitempty"`
	// List of the resulting values
	Value                []LoadTest `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedLoadTestList PaginatedLoadTestList

// NewPaginatedLoadTestList instantiates a new PaginatedLoadTestList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedLoadTestList(value []LoadTest) *PaginatedLoadTestList {
	this := PaginatedLoadTestList{}
	this.Value = value
	return &this
}

// NewPaginatedLoadTestListWithDefaults instantiates a new PaginatedLoadTestList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedLoadTestListWithDefaults() *PaginatedLoadTestList {
	this := PaginatedLoadTestList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedLoadTestList) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedLoadTestList) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedLoadTestList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PaginatedLoadTestList) SetCount(v int32) {
	o.Count = &v
}

// GetNextLink returns the NextLink field value if set, zero value otherwise.
func (o *PaginatedLoadTestList) GetNextLink() string {
	if o == nil || IsNil(o.NextLink) {
		var ret string
		return ret
	}
	return *o.NextLink
}

// GetNextLinkOk returns a tuple with the NextLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedLoadTestList) GetNextLinkOk() (*string, bool) {
	if o == nil || IsNil(o.NextLink) {
		return nil, false
	}
	return o.NextLink, true
}

// HasNextLink returns a boolean if a field has been set.
func (o *PaginatedLoadTestList) HasNextLink() bool {
	if o != nil && !IsNil(o.NextLink) {
		return true
	}

	return false
}

// SetNextLink gets a reference to the given string and assigns it to the NextLink field.
func (o *PaginatedLoadTestList) SetNextLink(v string) {
	o.NextLink = &v
}

// GetValue returns the Value field value
func (o *PaginatedLoadTestList) GetValue() []LoadTest {
	if o == nil {
		var ret []LoadTest
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaginatedLoadTestList) GetValueOk() ([]LoadTest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *PaginatedLoadTestList) SetValue(v []LoadTest) {
	o.Value = v
}

func (o PaginatedLoadTestList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedLoadTestList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["@count"] = o.Count
	}
	if !IsNil(o.NextLink) {
		toSerialize["@nextLink"] = o.NextLink
	}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedLoadTestList) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varPaginatedLoadTestList := _PaginatedLoadTestList{}

	err = json.Unmarshal(data, &varPaginatedLoadTestList)

	if err != nil {
		return err
	}

	*o = PaginatedLoadTestList(varPaginatedLoadTestList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "@count")
		delete(additionalProperties, "@nextLink")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedLoadTestList struct {
	value *PaginatedLoadTestList
	isSet bool
}

func (v NullablePaginatedLoadTestList) Get() *PaginatedLoadTestList {
	return v.value
}

func (v *NullablePaginatedLoadTestList) Set(val *PaginatedLoadTestList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedLoadTestList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedLoadTestList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedLoadTestList(val *PaginatedLoadTestList) *NullablePaginatedLoadTestList {
	return &NullablePaginatedLoadTestList{value: val, isSet: true}
}

func (v NullablePaginatedLoadTestList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedLoadTestList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
