/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
	"time"
)

// checks if the PatchedScheduleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedScheduleRequest{}

// PatchedScheduleRequest struct for PatchedScheduleRequest
type PatchedScheduleRequest struct {
	// The date after which the schedule will start running the test.
	Starts               *time.Time                     `json:"starts,omitempty"`
	Repeats              *PatchedScheduleRequestRepeats `json:"repeats,omitempty"`
	Ends                 *PatchedScheduleRequestEnds    `json:"ends,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedScheduleRequest PatchedScheduleRequest

// NewPatchedScheduleRequest instantiates a new PatchedScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedScheduleRequest() *PatchedScheduleRequest {
	this := PatchedScheduleRequest{}
	return &this
}

// NewPatchedScheduleRequestWithDefaults instantiates a new PatchedScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedScheduleRequestWithDefaults() *PatchedScheduleRequest {
	this := PatchedScheduleRequest{}
	return &this
}

// GetStarts returns the Starts field value if set, zero value otherwise.
func (o *PatchedScheduleRequest) GetStarts() time.Time {
	if o == nil || IsNil(o.Starts) {
		var ret time.Time
		return ret
	}
	return *o.Starts
}

// GetStartsOk returns a tuple with the Starts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedScheduleRequest) GetStartsOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Starts) {
		return nil, false
	}
	return o.Starts, true
}

// HasStarts returns a boolean if a field has been set.
func (o *PatchedScheduleRequest) HasStarts() bool {
	if o != nil && !IsNil(o.Starts) {
		return true
	}

	return false
}

// SetStarts gets a reference to the given time.Time and assigns it to the Starts field.
func (o *PatchedScheduleRequest) SetStarts(v time.Time) {
	o.Starts = &v
}

// GetRepeats returns the Repeats field value if set, zero value otherwise.
func (o *PatchedScheduleRequest) GetRepeats() PatchedScheduleRequestRepeats {
	if o == nil || IsNil(o.Repeats) {
		var ret PatchedScheduleRequestRepeats
		return ret
	}
	return *o.Repeats
}

// GetRepeatsOk returns a tuple with the Repeats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedScheduleRequest) GetRepeatsOk() (*PatchedScheduleRequestRepeats, bool) {
	if o == nil || IsNil(o.Repeats) {
		return nil, false
	}
	return o.Repeats, true
}

// HasRepeats returns a boolean if a field has been set.
func (o *PatchedScheduleRequest) HasRepeats() bool {
	if o != nil && !IsNil(o.Repeats) {
		return true
	}

	return false
}

// SetRepeats gets a reference to the given PatchedScheduleRequestRepeats and assigns it to the Repeats field.
func (o *PatchedScheduleRequest) SetRepeats(v PatchedScheduleRequestRepeats) {
	o.Repeats = &v
}

// GetEnds returns the Ends field value if set, zero value otherwise.
func (o *PatchedScheduleRequest) GetEnds() PatchedScheduleRequestEnds {
	if o == nil || IsNil(o.Ends) {
		var ret PatchedScheduleRequestEnds
		return ret
	}
	return *o.Ends
}

// GetEndsOk returns a tuple with the Ends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedScheduleRequest) GetEndsOk() (*PatchedScheduleRequestEnds, bool) {
	if o == nil || IsNil(o.Ends) {
		return nil, false
	}
	return o.Ends, true
}

// HasEnds returns a boolean if a field has been set.
func (o *PatchedScheduleRequest) HasEnds() bool {
	if o != nil && !IsNil(o.Ends) {
		return true
	}

	return false
}

// SetEnds gets a reference to the given PatchedScheduleRequestEnds and assigns it to the Ends field.
func (o *PatchedScheduleRequest) SetEnds(v PatchedScheduleRequestEnds) {
	o.Ends = &v
}

func (o PatchedScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Starts) {
		toSerialize["starts"] = o.Starts
	}
	if !IsNil(o.Repeats) {
		toSerialize["repeats"] = o.Repeats
	}
	if !IsNil(o.Ends) {
		toSerialize["ends"] = o.Ends
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedScheduleRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedScheduleRequest := _PatchedScheduleRequest{}

	err = json.Unmarshal(data, &varPatchedScheduleRequest)

	if err != nil {
		return err
	}

	*o = PatchedScheduleRequest(varPatchedScheduleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "starts")
		delete(additionalProperties, "repeats")
		delete(additionalProperties, "ends")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedScheduleRequest struct {
	value *PatchedScheduleRequest
	isSet bool
}

func (v NullablePatchedScheduleRequest) Get() *PatchedScheduleRequest {
	return v.value
}

func (v *NullablePatchedScheduleRequest) Set(val *PatchedScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedScheduleRequest(val *PatchedScheduleRequest) *NullablePatchedScheduleRequest {
	return &NullablePatchedScheduleRequest{value: val, isSet: true}
}

func (v NullablePatchedScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
