/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the PaginatedLoadZoneList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedLoadZoneList{}

// PaginatedLoadZoneList struct for PaginatedLoadZoneList
type PaginatedLoadZoneList struct {
	// Object count in the collection
	Count *int32 `json:"@count,omitempty"`
	// A reference to the next page of results. The property is included until there are no more pages of results to retrieve.
	NextLink *string `json:"@nextLink,omitempty"`
	// List of the resulting values
	Value                []LoadZone `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedLoadZoneList PaginatedLoadZoneList

// NewPaginatedLoadZoneList instantiates a new PaginatedLoadZoneList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedLoadZoneList(value []LoadZone) *PaginatedLoadZoneList {
	this := PaginatedLoadZoneList{}
	this.Value = value
	return &this
}

// NewPaginatedLoadZoneListWithDefaults instantiates a new PaginatedLoadZoneList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedLoadZoneListWithDefaults() *PaginatedLoadZoneList {
	this := PaginatedLoadZoneList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedLoadZoneList) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedLoadZoneList) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedLoadZoneList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PaginatedLoadZoneList) SetCount(v int32) {
	o.Count = &v
}

// GetNextLink returns the NextLink field value if set, zero value otherwise.
func (o *PaginatedLoadZoneList) GetNextLink() string {
	if o == nil || IsNil(o.NextLink) {
		var ret string
		return ret
	}
	return *o.NextLink
}

// GetNextLinkOk returns a tuple with the NextLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedLoadZoneList) GetNextLinkOk() (*string, bool) {
	if o == nil || IsNil(o.NextLink) {
		return nil, false
	}
	return o.NextLink, true
}

// HasNextLink returns a boolean if a field has been set.
func (o *PaginatedLoadZoneList) HasNextLink() bool {
	if o != nil && !IsNil(o.NextLink) {
		return true
	}

	return false
}

// SetNextLink gets a reference to the given string and assigns it to the NextLink field.
func (o *PaginatedLoadZoneList) SetNextLink(v string) {
	o.NextLink = &v
}

// GetValue returns the Value field value
func (o *PaginatedLoadZoneList) GetValue() []LoadZone {
	if o == nil {
		var ret []LoadZone
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaginatedLoadZoneList) GetValueOk() ([]LoadZone, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *PaginatedLoadZoneList) SetValue(v []LoadZone) {
	o.Value = v
}

func (o PaginatedLoadZoneList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedLoadZoneList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["@count"] = o.Count
	}
	if !IsNil(o.NextLink) {
		toSerialize["@nextLink"] = o.NextLink
	}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedLoadZoneList) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varPaginatedLoadZoneList := _PaginatedLoadZoneList{}

	err = json.Unmarshal(data, &varPaginatedLoadZoneList)

	if err != nil {
		return err
	}

	*o = PaginatedLoadZoneList(varPaginatedLoadZoneList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "@count")
		delete(additionalProperties, "@nextLink")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedLoadZoneList struct {
	value *PaginatedLoadZoneList
	isSet bool
}

func (v NullablePaginatedLoadZoneList) Get() *PaginatedLoadZoneList {
	return v.value
}

func (v *NullablePaginatedLoadZoneList) Set(val *PaginatedLoadZoneList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedLoadZoneList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedLoadZoneList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedLoadZoneList(val *PaginatedLoadZoneList) *NullablePaginatedLoadZoneList {
	return &NullablePaginatedLoadZoneList{value: val, isSet: true}
}

func (v NullablePaginatedLoadZoneList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedLoadZoneList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
