/*


HTTP API for interacting with k6 Cloud.

API version: 0.0.0
Contact: info@grafana.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k6

import (
	"encoding/json"
)

// checks if the ValidateOptionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateOptionsResponse{}

// ValidateOptionsResponse struct for ValidateOptionsResponse
type ValidateOptionsResponse struct {
	// How many VUh will be charged for the test
	VuhUsage             float64 `json:"vuh_usage"`
	AdditionalProperties map[string]interface{}
}

type _ValidateOptionsResponse ValidateOptionsResponse

// NewValidateOptionsResponse instantiates a new ValidateOptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateOptionsResponse(vuhUsage float64) *ValidateOptionsResponse {
	this := ValidateOptionsResponse{}
	this.VuhUsage = vuhUsage
	return &this
}

// NewValidateOptionsResponseWithDefaults instantiates a new ValidateOptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateOptionsResponseWithDefaults() *ValidateOptionsResponse {
	this := ValidateOptionsResponse{}
	return &this
}

// GetVuhUsage returns the VuhUsage field value
func (o *ValidateOptionsResponse) GetVuhUsage() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.VuhUsage
}

// GetVuhUsageOk returns a tuple with the VuhUsage field value
// and a boolean to check if the value has been set.
func (o *ValidateOptionsResponse) GetVuhUsageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VuhUsage, true
}

// SetVuhUsage sets field value
func (o *ValidateOptionsResponse) SetVuhUsage(v float64) {
	o.VuhUsage = v
}

func (o ValidateOptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateOptionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vuh_usage"] = o.VuhUsage

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidateOptionsResponse) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varValidateOptionsResponse := _ValidateOptionsResponse{}

	err = json.Unmarshal(data, &varValidateOptionsResponse)

	if err != nil {
		return err
	}

	*o = ValidateOptionsResponse(varValidateOptionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vuh_usage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidateOptionsResponse struct {
	value *ValidateOptionsResponse
	isSet bool
}

func (v NullableValidateOptionsResponse) Get() *ValidateOptionsResponse {
	return v.value
}

func (v *NullableValidateOptionsResponse) Set(val *ValidateOptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateOptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateOptionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateOptionsResponse(val *ValidateOptionsResponse) *NullableValidateOptionsResponse {
	return &NullableValidateOptionsResponse{value: val, isSet: true}
}

func (v NullableValidateOptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateOptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
